import Recipe from "@/app/lib/model/recipe_model";
import RecipeCard from "@/app/components/recipe_card";
import Image from "next/image";


// Define the structure of a single chat entry
export type RecipeGeneratorProps = {
    contentType: "text" | "image" | "recipes"; // Possible content types
    content: string; // The actual content (text or image URL)
    recipes: Recipe[];
    author: "user" | "bot"; // The sender of the content
};

// Component to render individual chat entries
export const RequestContent: React.FC<{ content: RecipeGeneratorProps }> = ({
    content,
}) => {
    const { contentType, content: contentData, recipes, author } = content;
    let view = <></>

    if (contentType === "text") {
        view = (
            <div className="px-2 py-1 text-sm rounded-lg">
                {contentData}
            </div>
        );
    } else if (contentType === "image") {
        view = (
            <div className="rounded-xl overflow-hidden h-36 w-fit">
                <Image
                    src={contentData}
                    alt="Image generated by the AI"
                    className="w-full h-full object-cover"
                    width={640}
                    height={640}
                />
            </div>
        );
    } else if (contentType === "recipes") {
        view = (
            <div className="w-full p-1 space-y-2">
                {recipes.map((recipe, index) => {
                    return <RecipeCard key={index} recipe={recipe} />
                })}
            </div>
        )
    }

    return (
        <div
            className={`rounded-2xl overflow-hidden ${author === "user" ? "bg-slate-800 text-white place-self-end mt-4 mb-1 ml-12" : " bg-slate-100 mr-12"
                } `}
        >
            {view}
        </div>
    );
}