import Recipe from "@/app/data/model/recipe_model";
import RecipeCard from "@/app/components/recipe_card";
import Image from "next/image";


// Define the structure of a single chat entry
export type RecipeGeneratorProps = {
    contentType: "text" | "image" | "recipes"; // Possible content types
    content: string; // The actual content (text or image URL)
    recipes: Recipe[];
    author: "user" | "bot"; // The sender of the content
};

// Component to render individual chat entries
export const RequestContent: React.FC<{ content: RecipeGeneratorProps }> = ({
                                                                                content,
                                                                            }) => {
    const {contentType, content: contentData, recipes, author} = content;
    let view = <></>

    if (contentType === "text") {
        view = (
            <div className="p-2 text-sm rounded-lg">
                {contentData}
            </div>
        );
    } else if (contentType === "image") {
        view = (
            <div className="rounded-xl overflow-hidden">
                <Image
                    src={contentData}
                    alt="Image generated by the AI"
                    className="w-full h-full object-cover"
                    width={800}
                    height={800}
                />
            </div>
        );
    } else if (contentType === "recipes") {
        view = (
            <div className=" space-y-2 bg-white">
                {recipes.map((recipe, index) => {
                    return <RecipeCard key={index} recipe={recipe}/>
                })}
            </div>
        )
    }

    return (
        <div className={`flex ${author === "user" ? "justify-end " : "justify-start"
        }`}>
            <div
                className={`w-4/5 rounded-xl overflow-hidden ${author === "user" ? "bg-slate-800 text-white" : " bg-slate-100"
                } `}
            >
                {view}
            </div>
        </div>
    );
}